spring:
  session:
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:postgresql://localhost:5435/todo_manager
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver